export const GENERAL_ACTIONS = {
  GET_LIST_REQUEST: "GET_LIST_REQUEST",
  GET_LIST_SUCCESS: "GET_LIST_SUCCESS",
  GET_LIST_FAILURE: "GET_LIST_FAILURE",

  CLEAR_LIST_REQUEST: "CLEAR_LIST_REQUEST",

  GET_DATA_REQUEST: "GET_DATA_REQUEST",
  GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
  GET_DATA_FAILURE: "GET_DATA_FAILURE",

  UPDATE_POST_DATA_REQUEST: "UPDATE_POST_DATA_REQUEST",

  POST_DATA_REQUEST: "POST_DATA_REQUEST",
  POST_DATA_SUCCESS: "POST_DATA_SUCCESS",
  POST_DATA_FAILURE: "POST_DATA_FAILURE",

  UPDATE_DATA_REQUEST: "UPDATE_DATA_REQUEST",
  UPDATE_DATA_SUCCESS: "UPDATE_DATA_SUCCESS",
  UPDATE_DATA_FAILURE: "UPDATE_DATA_FAILURE",

  UPDATE_SINGLE_LIST_RECORD_REQUEST: "UPDATE_SINGLE_LIST_RECORD_REQUEST",

  DELETE_DATA_REQUEST: "DELETE_DATA_REQUEST",
  DELETE_DATA_SUCCESS: "DELETE_DATA_SUCCESS",
  DELETE_DATA_FAILURE: "DELETE_DATA_FAILURE",

  FILTER_COUNT: "FILTER_COUNT",

  SAVE_FILTER: "SAVE_FILTER",

  SAVE_VIEW: "SAVE_VIEW",
};

export const QURAN_ACTIONS = {
  GET_CHAPTER_LIST_REQUEST: "GET_CHAPTER_LIST_REQUEST",
  GET_CHAPTER_LIST_SUCCESS: "GET_CHAPTER_LIST_SUCCESS",
  GET_CHAPTER_LIST_FAILURE: "GET_CHAPTER_LIST_FAILURE",
};
