export const BASE_URL_KEY = {
  ADVANCE: "advance",
  NETWORK: "network",
};

export const LOCAL_STORAGE_KEYS = {
  USER: "VYTELLE_USER_INFO",
  ACCESS_TOKEN: "VYTELE_ACCESS",
  CONFIGURATION: "VYTELLE_CONFIGURATION",
  PERMISSIONS: "VYTELLE_PERMISSIONS",
  LAST_SYNC: "VYTELLE_LAST_SYNC",
  LAST_SYNC_UI: "VYTELLE_LAST_SYNC_UI",
  LAST_SYNC_LOCATION: "VYTELLE_LAST_SYNC_LOCATION",
  USER_DOMAIN: "VYTELLE_USER_DOMAIN",
  CURRENT_APPLICATION: "VYTELLE_CURRENT_APPLICATION",
  LANGUAGE: "VYTELLE_LANGUAGE",
  USER_ROLE: "VYTELLE_USER_ROLE",
  USER_TYPE: "VYTELLE_USER_TYPE",

  USER_PREFERENCES: "USER_PREFERENCES",
  MULTIPLE_ROLES: "MULTIPLE_ROLES",
};

export const ERROR_TYPE_MSG = {
  PRE_CONDITION: "Pre condition error",
};